/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemacompuwork.Presentacion;


import java.awt.Color;


/**
 *
 * @author duvia
 */
public class ReporteDesempeño extends javax.swing.JDialog {
    private final Ventana ventanaPrincipal;

    /**
     * Creates new form ReporteDesempeño
     */
    public ReporteDesempeño(java.awt.Frame parent, boolean modal, Ventana ventana) {
        super(parent, modal);
        initComponents();
        this.ventanaPrincipal = ventana;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDesempeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDesempeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDesempeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDesempeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteDesempeño dialog = new ReporteDesempeño(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDReporte = new javax.swing.JTextField();
        txtNombreReporte = new javax.swing.JTextField();
        txtFechaReporte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Box1TipoEmpleado = new javax.swing.JComboBox<>();
        Box2ReporteDesempeño = new javax.swing.JComboBox<>();
        btnGuardarDesempeño = new javax.swing.JToggleButton();
        btnLimpiarDesempeño = new javax.swing.JToggleButton();
        btnSalirDesempeño = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reporte Desempeño");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(" ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Fecha Reporte");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Reporte Desempeño");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tipo Empleado");

        Box1TipoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Box1TipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                Seleccione", "Empleado Vinculado", "Empleado Temporal" }));
        Box1TipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1TipoEmpleadoActionPerformed(evt);
            }
        });

        Box2ReporteDesempeño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Box2ReporteDesempeño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                 Seleccione", "Excelente", "Bueno", "Regular", "Deficiente" }));

        btnGuardarDesempeño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarDesempeño.setText("Guardar");
        btnGuardarDesempeño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarDesempeñoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarDesempeñoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarDesempeñoMouseExited(evt);
            }
        });
        btnGuardarDesempeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDesempeñoActionPerformed(evt);
            }
        });

        btnLimpiarDesempeño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarDesempeño.setText("Limpiar");
        btnLimpiarDesempeño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarDesempeñoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarDesempeñoMouseExited(evt);
            }
        });
        btnLimpiarDesempeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDesempeñoActionPerformed(evt);
            }
        });

        btnSalirDesempeño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirDesempeño.setText("Salir");
        btnSalirDesempeño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirDesempeñoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirDesempeñoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirDesempeñoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnGuardarDesempeño)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLimpiarDesempeño)
                        .addGap(98, 98, 98)
                        .addComponent(btnSalirDesempeño))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFechaReporte)
                        .addComponent(txtIDReporte)
                        .addComponent(txtNombreReporte)
                        .addComponent(Box1TipoEmpleado, 0, 181, Short.MAX_VALUE)
                        .addComponent(Box2ReporteDesempeño, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Box1TipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Box2ReporteDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDesempeño)
                    .addComponent(btnLimpiarDesempeño)
                    .addComponent(btnSalirDesempeño))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box1TipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1TipoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box1TipoEmpleadoActionPerformed

    private void btnGuardarDesempeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDesempeñoActionPerformed
        String id = txtIDReporte.getText();
    String nombre = txtNombreReporte.getText();
    String fechaReporte = txtFechaReporte.getText();
    String tipoEmpleado = (String) Box1TipoEmpleado.getSelectedItem();
    String valoracion = (String) Box2ReporteDesempeño.getSelectedItem();

    }//GEN-LAST:event_btnGuardarDesempeñoActionPerformed

    private void btnGuardarDesempeñoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarDesempeñoMouseEntered
        btnGuardarDesempeño.setBackground(new Color(239,243,7));
    }//GEN-LAST:event_btnGuardarDesempeñoMouseEntered

    private void btnGuardarDesempeñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarDesempeñoMouseClicked
        
    }//GEN-LAST:event_btnGuardarDesempeñoMouseClicked

    private void btnGuardarDesempeñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarDesempeñoMouseExited
       btnGuardarDesempeño.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnGuardarDesempeñoMouseExited

    private void btnLimpiarDesempeñoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarDesempeñoMouseEntered
        btnLimpiarDesempeño.setBackground(new Color(239,243,7));
    }//GEN-LAST:event_btnLimpiarDesempeñoMouseEntered

    private void btnLimpiarDesempeñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarDesempeñoMouseExited
       btnLimpiarDesempeño.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnLimpiarDesempeñoMouseExited

    private void btnSalirDesempeñoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirDesempeñoMouseEntered
        btnSalirDesempeño.setBackground(new Color(239,243,7));
    }//GEN-LAST:event_btnSalirDesempeñoMouseEntered

    private void btnSalirDesempeñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirDesempeñoMouseExited
         btnSalirDesempeño.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSalirDesempeñoMouseExited

    private void btnSalirDesempeñoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirDesempeñoMousePressed
         System.exit(0);
    }//GEN-LAST:event_btnSalirDesempeñoMousePressed

    private void btnLimpiarDesempeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDesempeñoActionPerformed
         txtIDReporte.setText("");
         txtNombreReporte.setText("");
         txtFechaReporte.setText("");
         Box1TipoEmpleado.setSelectedIndex(0);
         Box2ReporteDesempeño.setSelectedIndex(0); 
 
    }//GEN-LAST:event_btnLimpiarDesempeñoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box1TipoEmpleado;
    private javax.swing.JComboBox<String> Box2ReporteDesempeño;
    private javax.swing.JToggleButton btnGuardarDesempeño;
    private javax.swing.JToggleButton btnLimpiarDesempeño;
    private javax.swing.JToggleButton btnSalirDesempeño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFechaReporte;
    private javax.swing.JTextField txtIDReporte;
    private javax.swing.JTextField txtNombreReporte;
    // End of variables declaration//GEN-END:variables
}
